### ISSUE TITLE
handleOpenURL应该返回BOOL类型

### ISSUE THREAD

**Issue by phaibin** [PingPlusPlus/pingpp-ios#10]
各种回调的SDK都会用appdelegate的openURL方法来处理，handleOpenURL应该返回BOOL类型代表你能不能处理，你这样只能把Pingpp的处理放在最后一个else里面。如果还有别的SDK不返回BOOL类型，那就死翘翘了

**Comment by samurai00** [comment]
这部分，我们会改进。
