### ISSUE TITLE
 "_OBJC_CLASS_$_AlipaySDK", referenced from:

### ISSUE THREAD

**Issue by Mr-nan** [PingPlusPlus/pingpp-ios#101]
<img width="619" alt="WeChatf3bb1a3cc1afa5bde70a679dbc3c34dc" src="https://user-images.githubusercontent.com/17428078/71613321-c66e2f80-2be0-11ea-833c-1148fc6e540f.png">

**Comment by samurai00** [comment]
你是通过 cocoapods 导入的吗？
如果不是的话，那么要确保，alipay 的 framework 已经正确导入到项目。

**Comment by Mr-nan** [comment]
@samurai00 手动导入；alipay 的 framework 已导入

**Comment by samurai00** [comment]
手动导入的话，就跟你的项目配置有很大关系了。

检查一下 Build Settings 里各个 Search Paths 有没有把你“导入”的 AlipaySDK.framework 的目录包含进去。

试试直接调用一下 AlipaySDK 里的方法，看看能不能编译通过。

先 import

Objective-C 的话

```objective-c
#import <AlipaySDK/AlipaySDK.h>
```

```objective-c
[[AlipaySDK defaultService] currentVersion];
```

Swift 的话，通过 -Bridging-Header.h 或者 .modulemap

```swift
AlipaySDK.defaultService()?.currentVersion()
```

如果这个调用编译不过，那就还是没导入正确。
