### ISSUE TITLE
pingpp SDK 需要更新一下版本 提交到App Store 显示项目中带UIWebView

### ISSUE THREAD

**Issue by WuZhuoXuan** [PingPlusPlus/pingpp-ios#103]
grep -r UIWebView。
二进制文件./WorkGo.xcworkspace/xcuserdata/wuzhuoxuan.xcuserdatad/UserInterfaceState.xcuserstate匹配
二进制文件./Pods/Pingpp/lib/Channels/UnionPay/libPaymentControl.a匹配

什么时候解决一下

**Comment by samurai00** [comment]
你这个应该是旧的版本。你清一下 pod cache，再更新一下版本号。重新 pod install 一下。

**Comment by WuZhuoXuan** [comment]
grep -r UIWebView .
Binary file ./workGo/Pods/Pingpp/lib/Channels/UnionPay/libPaymentControl.a matches

pod版本2.2.23

还是有相同的问题

**Comment by samurai00** [comment]
最新版本是 2.2.30
