### ISSUE TITLE
集成的微信SDK版本太低

### ISSUE THREAD

**Issue by phaibin** [PingPlusPlus/pingpp-ios#11]
不知道集成的微信SDK是什么版本的，能不能升级到最新版本？

**Comment by samurai00** [comment]
微信官方最新的是 1.5 的。如果你用的是我们最新版本的 SDK，直接把微信最新的静态库文件替换掉我们提供的就可以了。

**Comment by phaibin** [comment]
可以把cocoapods文件列表里面的微信静态库去掉么，这样我就可以自己加微信静态库了

**Comment by samurai00** [comment]
用 cocoapods 我建议你先把我们的 SDK clone 到本地，然后在 Podfile 里类似这么写
`pod 'AFNetworking', :path => '~/Documents/AFNetworking'`
然后，把本地微信的库换掉。
