### ISSUE TITLE
测试模式的适合，，支付成功，，后台收到通知结果，而APP端却没有收到

### ISSUE THREAD

**Issue by wwwang89** [PingPlusPlus/pingpp-ios#12]
测试模式的适合，是跳转到Safari的网页页面的，支付宝支付成功，，后台收到通知结果，而APP端却没有收到支付通知，且点击“付款”按钮之后，，就出现“页面不存在，链接失效等”，这 是什么原因呢？谢谢！

**Comment by burulangtu** [comment]
可能的解决方案：请修改 Info 里的 URL Types，添加自己的 URL Schemes。
如果依旧不能解决，请联系技术支持QQ：800102802。
