### ISSUE TITLE
壹收款的SDK不支持swift版本

### ISSUE THREAD

**Issue by cloud-hot** [PingPlusPlus/pingpp-ios#14]
当按照文档要求安装壹收款sdk后，并将#import "Pingpp.h"导入到swift与objc的bridge header后编译不通过。

![Uploading 屏幕快照 2015-07-15 上午8.49.58.png…]()

**Comment by cloud-hot** [comment]
图片怎么都上传不上去
+ (void)createPayment:(NSString *)charge viewController:(UIViewController *)viewController appURLScheme:(NSString *)scheme delegate:(id<PingppDelegate>)delegate __attribute__((deprecated));
这段报“swift compiler error expected a type”

**Comment by samurai00** [comment]
我这边编译没问题。你贴的这段是废弃的方法。你调用的是这个方法吗？
```
Pingpp.payWithOrderNo("ordernoabcdefgjksld", amount: 10, display: [], serverURL: "http://192.168.1.123/tests/pay.php", viewController: self) { (result, error) -> Void in
    if error != nil {
        println(error.code.rawValue)
        println(error.getMsg())
    }
    println(result)
}
```

**Comment by cloud-hot** [comment]
没有，我只是将这个header放到bridge header中先编译，没有调用任何api

Xcode6.4

你那边能否提交一个swift的example，类似其他branch中的example

**Comment by cloud-hot** [comment]
我使用的是alipay_wx_upmp_checkout branch 如果是master branch的话里面的swift example我也可以编译过的

**Comment by samurai00** [comment]
@cloud-hot example 发你邮箱了，你试一下。

**Comment by cloud-hot** [comment]
ok，谢谢！不过我刚才找到问题了
+ (void)createPayment:(NSString *)charge viewController:(UIViewController *)viewController appURLScheme:(NSString *)scheme delegate:(id<PingppDelegate>)delegate __attribute__((deprecated));
中有UIViewController但是Pingpp.h中却没有#import <UIKit/UIKit.h>

这样就需要import Pingpp.h时前面必须先#import <UIKit/UIKit.h>

这个要求合适吗？

**Comment by allenwong** [comment]
@samurai00 您也可以发这个 Swift Example 到我的邮箱吗？或者您方便更新上来吗？
openallen@gmail.com
