### ISSUE TITLE
希望 Pingxx 可以自己像其他第三方 SDK 那样，处理 AppDelegate 里面的回调。

### ISSUE THREAD

**Issue by rpplusplus** [PingPlusPlus/pingpp-ios#17]
对于使用者而言，两个地方会有回调就必须封装一次 才能使用 实在是太不友好了....

**Comment by samurai00** [comment]
`[Pingpp handleOpenURL:url withCompletion:nil];`
这个方法传 nil 就会在一个地方回调了。
