### ISSUE TITLE
Invalid Channel

### ISSUE THREAD

**Issue by rpplusplus** [PingPlusPlus/pingpp-ios#18]
阿里百川的 AliPay SDK 是 2.0 
Ping++ AliPay SDK 是 2.1
当同时使用的时候，若选择 2.0 为基础 SDK，Ping++  会提示 Invalid Channel。

这个 问题找了好久才找到原因...

**Comment by samurai00** [comment]
`[[AlipaySDK defaultService] currentVersion]`
打印出来是什么？
如果只是替换 Alipay 的 SDK 的话，应该是可以的。

**Comment by rpplusplus** [comment]
@samurai00 不只是替换啊...还要降级啊....从 2.1 -> 2.0

**Comment by samurai00** [comment]
@rpplusplus  2.1 和 2.0 的接口没有变过。应该是可以调用的。

**Comment by rpplusplus** [comment]
@samurai00 但就是提示 Invalid Channel......如果用 2.1 没有这个问题...但我担心百川那头会出问题...
