### ISSUE TITLE
XCode6.4，Cocoapods 0.38.2 安装"Pingpp/Wx", "~> 2.1.0" link时报Undefined symbols for architecture arm64

### ISSUE THREAD

**Issue by ErosZy** [PingPlusPlus/pingpp-ios#19]
RT

**Comment by samurai00** [comment]
你看一下 `Podfile.lock` 里的版本号是什么

**Comment by ErosZy** [comment]
Podfile.lock里面的版本号是2.1.3

**Comment by samurai00** [comment]
把具体报错贴一下吧

**Comment by ErosZy** [comment]
手动导入同样出现相同问题

Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_PingppInternal", referenced from:
      l_OBJC_$_CATEGORY_PingppInternal_$_Alipay in libpingpp+alipay.a(PingppInternal+Alipay.o)
      l_OBJC_$_CATEGORY_PingppInternal_$_Wx in libpingpp+wx.a(PingppInternal+Wx.o)
  "_OBJC_CLASS_$_PingppUtil", referenced from:
      objc-class-ref in libpingpp+alipay.a(PingppInternal+Alipay.o)
      objc-class-ref in libpingpp+wx.a(PingppInternal+Wx.o)
  "_PingppLocalizedString", referenced from:
      -[PingppInternal(Alipay) alipayResult:] in libpingpp+alipay.a(PingppInternal+Alipay.o)
      -[PingppInternal(Wx) onResp:] in libpingpp+wx.a(PingppInternal+Wx.o)
ld: symbol(s) not found for architecture arm64

**Comment by samurai00** [comment]
你把编译缓存目录的文件清空一下再试。

**Comment by ErosZy** [comment]
![p1](http://7xijan.com1.z0.glb.clouddn.com/QQ图片20150919162352.jpg)
![p2](http://7xijan.com1.z0.glb.clouddn.com/QQ图片20150919162346.jpg)

删除编译缓存目录文件后仍然如此，在link阶段报相同错误。

**Comment by samurai00** [comment]
可能是编译缓存没删干净吧。目录会有真机的和模拟器的两个。
