### ISSUE TITLE
调起模拟支付控件后点付款没有结果

### ISSUE THREAD

**Issue by xz410236056** [PingPlusPlus/pingpp-ios#26]
点付款后显示支付过程尚未完成

代码什么的都是复制demo，demo里可以完成支付，而我的不行
- (IBAction)pay:(UIButton *)sender {
    if (_PayText.text.integerValue <10) {
        [MBProgressHUD showError:@"驾币数小于10"];
    }
    else
    {
     
        
        NSString *orderNo = [TradeNumber generateTradeNO]; //订单号
        NSString* money = [NSString stringWithFormat:@"%ld",(long)[_PayText.text integerValue]*10];
        NSString* num =[NSString stringWithFormat:@"%ld",(long)[_PayText.text integerValue]];
        NSArray *contents = @[
                           @[
                               @"驾币", @[num]
                            ]
                           ];
        [Pingpp payWithOrderNo:orderNo
                        amount:money.integerValue
                       display:contents
                     serverURL:kServerUrl
                  appURLScheme:@"JJxueche"
             completionHandler:^(NSString *result, PingppError *error) {
    
                 NSLog(@"成功:%@\n失败:%@\n",result,[error getMsg]);
             }];
    }
    
}

**Comment by xz410236056** [comment]
找到原因了。不知道是不是iOS9的原因

appdelegate里并不是调用
- (BOOL)application:(UIApplication *)application openURL:(NSURL *)url sourceApplication:(NSString *)sourceApplication
而是要调用
-(BOOL)application:(UIApplication *)app openURL:(NSURL *)url options:(NSDictionary<NSString *,id> *)options

**Comment by samurai00** [comment]
是的。是 iOS 9 换成新的方法，弃用了原来的。
文档我们正在更新。
