### ISSUE TITLE
不能push或presend支付宝的wap页面

### ISSUE THREAD

**Issue by shenjian19** [PingPlusPlus/pingpp-ios#27]
碰到一个很奇异的事，某种未知情况下，没有装支付宝App的手机只能停留在原页，不能跳转到支付宝的wap页。但是如果参数传入错误格式是可以进入block。但是创建一个新的干净工程直接调API，又可以跳，不知道跳转的判断条件如何界定的？

**Comment by samurai00** [comment]
如果你没有使用 storyboard 来进行页面布局的话，看一下 Info.plist 里是不是有 main storyboard file base name 之类的，把它删了，再试试。

**Comment by shenjian19** [comment]
没有使用storyboard，同时info.plist也清除干净的。把有问题的工程，其他所有依赖都清除，info.plist只保留最基础的，还是不行。而问题工程的info.plist拷贝到新工程，一样能用。能看下跳转条件有哪些？

**Comment by shenjian19** [comment]
找到问题，不知道为啥，和ShareSDK冲突，接入1.5版本的ShareSDK库后，即使不调用，也影响。更新到1.6，现象消失
