### ISSUE TITLE
微信支付崩溃，支付宝正常

### ISSUE THREAD

**Issue by huangjunsong** [PingPlusPlus/pingpp-ios#28]
调用createPayment接口，微信支付崩溃，支付宝正常，报错：
reason: '-[__NSCFNumber length]: unrecognized selector sent to instance
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by samurai00** [comment]
`charge` 的 `credential` 里有个字段 `partnerId`，那个必须是字符串。不能转成整型。
服务端处理 charge 的时候，不要自己转 JSON，直接拿 charge 对象当字符串使用。

**Comment by huangjunsong** [comment]
@samurai00 刚才已经和客服了解并且修复好了，感谢你的答复~~~
