### ISSUE TITLE
接入的时候Xcode 报错

### ISSUE THREAD

**Issue by SlightEvil** [PingPlusPlus/pingpp-ios#30]
ld: library not found for -lUPPayPlugin
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by samurai00** [comment]
Channels/UnionPay 这个目录导入了吗，是否需要使用银联渠道？

**Comment by liu36521** [comment]
同样的错误，所需渠道：微信、支付宝、银联
pod导入后，编译提示如上问题，请问如何解决

**Comment by samurai00** [comment]
@liu36521 pod 导入有没有报错。Pods 目录下的内容是否下载正常？

**Comment by liu36521** [comment]
pod 导入没有问题，内容也在。
之后，我们把example里的库手动导入了一下，就可以用了，也并没有进行其他配置，所以可能是pod导入的版本有一些设置的问题，期待完善。
