### ISSUE TITLE
swift项目使用cocoapods安装Pingpp，import的时候报错：No such module

### ISSUE THREAD

**Issue by tailang** [PingPlusPlus/pingpp-ios#32]
是使用use_frameworks!的原因吗？

**Comment by sharoni** [comment]
You need to add `#import <Pingpp.h>` to your aplication's bridging header.

**Comment by lawrenceching** [comment]
I installed the SDK using Pod successfully.
I've imported the Pingpp in my bridging header like this:
```
#import <MBProgressHUD/MBProgressHUD.h>
#import <WebViewJavascriptBridge/WebViewJavascriptBridge.h>
#import <Pingpp/Pingpp.h>
```

But it's not work. I'm new in iOS and Swift. I cannot figure out what is wrong.
Hope for help, thank you~

**Comment by sharoni** [comment]
@lawrenceching could you show how your Podfile looks like?

**Comment by lawrenceching** [comment]
Yes of cause.
```
# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

target 'PingxxDemo' do
    pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
    pod 'Alamofire', '~> 3.0'
    pod 'Kingfisher', '~> 2.0'
    pod 'TSMessages', :git => 'https://github.com/KrauseFx/TSMessages.git'
    pod 'MBProgressHUD', '~> 0.9.2'
    pod 'WebViewJavascriptBridge', '~> 5.0'
    pod 'Pingpp', '~> 2.2.0'
end

target 'PingxxDemoTests' do

end

target 'PingxxDemoUITests' do

end
```


I import the SDK in my view controller swift file
```
import Pingpp
```
Xcode shows up the "No such module" message.

**Comment by sharoni** [comment]
@lawrenceching you don't need to explicitly import it in swift files. You have already done so in bridging header. Remove the `import Pingpp` from swift file and just use Pingpp (e.g. try `Pingpp.setDebugMode(true)`) to see if it resolves the class.

**Comment by lawrenceching** [comment]
Thanks a lot! You make my day!
