### ISSUE TITLE
使用CocoaPods导入，CoCoaPods项目中没有Pingpp的target

### ISSUE THREAD

**Issue by iDalink** [PingPlusPlus/pingpp-ios#34]
使用CocoaPods导入，CoCoaPods项目中没有Pingpp的target。这是为什么呢？我的CocoPods的版本是0.39.0，Xcode版本是7.1。

**Comment by samurai00** [comment]
因为我们提供的都是静态库或者 framework 而不是源代码，所以是没有 target 的。
