### ISSUE TITLE
iOS「壹收款」在iOS9下点击支付宝微信渠道按钮无跳转

### ISSUE THREAD

**Issue by aiiaji** [PingPlusPlus/pingpp-ios#35]
iOS「壹收款」在iOS9下点击支付宝微信渠道按钮无跳转，界面上没有任何响应效果，项目急用，我们没有源码调试不了，能跟进一下吗？

**Comment by xz410236056** [comment]
我也遇到了同样的问题，请问是怎么解决的

**Comment by samurai00** [comment]
@xz410236056 按照文档添加URL Schemes 白名单和 http 协议请求许可了吗？

**Comment by aiiaji** [comment]
iOS9新项目需要允许访问htpp协议
