### ISSUE TITLE
壹收款目前已经合并到 SDK。但是在Pingpp.h中并没有壹收款的接口，如下方法接口

### ISSUE THREAD

**Issue by shenhongkai** [PingPlusPlus/pingpp-ios#36]
+ (void)payWithOrderNo:(NSString *)orderNo
                amount:(NSUInteger)amount
               display:(NSArray *)contents
             serverURL:(NSString *)url
          appURLScheme:(NSString *)scheme
        viewController:(UIViewController *)viewController
     completionHandler:(PingppCompletion)handler;

**Comment by samurai00** [comment]
https://github.com/PingPlusPlus/pingpp-ios/blob/master/lib/One/Pingpp%2BOne.h 在这里。
