### ISSUE TITLE
静态库

### ISSUE THREAD

**Issue by haoyongxin** [PingPlusPlus/pingpp-ios#39]
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_CMMotionManager", referenced from:
      objc-class-ref in AlipaySDK
ld: symbol(s) not found for architecture arm64
不支持64位？

**Comment by samurai00** [comment]
添加 coremotion 依赖库

**Comment by haoyongxin** [comment]
加了coreMotion库，还是不行。这还是只在官方中的demo运行就报这些错

**Comment by samurai00** [comment]
你加了 CoreMotion 报错肯定会变成其他的错。 demo 更新了。
