### ISSUE TITLE
pod 导入报错。。

### ISSUE THREAD

**Issue by EchoZuo** [PingPlusPlus/pingpp-ios#46]
错误如下：

[!] Error installing Pingpp
[!] /usr/bin/git clone https://github.com/PingPlusPlus/pingpp-ios.git /var/folders/rp/9pczbsgj0bs6bhf_0hxfjnb80000gn/T/d20160710-39365-19jr95f --template= --single-branch --depth 1 --branch 2.2.5

Cloning into '/var/folders/rp/9pczbsgj0bs6bhf_0hxfjnb80000gn/T/d20160710-39365-19jr95f'...
fatal: unable to access 'https://github.com/PingPlusPlus/pingpp-ios.git/': Failed to connect to github.com port 443: Operation timed out

试了好几遍都是这样，导入其他的类库没问题，

**Comment by samurai00** [comment]
你这个是连接超时了。你如果能下载下来，先下载下来，试试本地 pod。
