### ISSUE TITLE
需要单独导入微信SDK吗?

### ISSUE THREAD

**Issue by liufengyu** [PingPlusPlus/pingpp-ios#47]
pod 'Pingpp/Wx', '~>2.2.5'
pod 'Pingpp/Alipay', '~> 2.2.5'
没有看到微信SDK

**Comment by samurai00** [comment]
不需要。不需要微信的 SDK。

**Comment by liufengyu** [comment]
那如果需要判断微信是否安装的话,还需要单独导入微信的SDK吗?

**Comment by samurai00** [comment]
也不需要，你可以自己判断的。就是看看 weixin:// 这个能不能打开。

**Comment by liufengyu** [comment]
谢谢了
