### ISSUE TITLE
pod 'Pingpp/Alipay' 无法安装

### ISSUE THREAD

**Issue by BINDeveloper** [PingPlusPlus/pingpp-ios#50]
注释掉“pod 'Pingpp/Alipay'”以后pod update 没有问题，一打开“pod 'Pingpp/Alipay'”就报错，
半天没反应，就像没网一样，但是我的电脑是绝对有网的，望快点解决

**Comment by samurai00** [comment]
因为我们的库不是源码，另外，银联、支付宝的库也比较大，而且各种版本进入 git 库里。导致整体大小很大。所以直接 pod 会很慢，但是是可以的。建议你先下载下来，做本地 pod。用个快点的翻墙工具。
