### ISSUE TITLE
Master分支libs/Channels下没有Wx模块

### ISSUE THREAD

**Issue by Lautitia** [PingPlusPlus/pingpp-ios#51]
在使用cordova plugin add https://github.com/TongChia/cordova-plugin-pingpp.git\#all时报错
Failed to install 'me.tongchia.cordova.pingpp':CordovaError: Uh oh!
"/Users/joey/Documents/Cloud/src_code/EM/mobile/plugins/me.tongchia.cordova.pingpp/sdk/ios/lib/Channels/Wx/libpingpp+wx.a" not found!
分支下并无Wx模块，请问这个要怎么解决

**Comment by samurai00** [comment]
请看 readme。cordova 的问题，请找作者。
