### ISSUE TITLE
Undefined symbols for architecture arm64:   "_OBJC_CLASS_$_CLLocationManager", referenced from:       objc-class-ref in libBaiduMobStatForSDK.a(BaiduMobStatLogManagerForSDK.o)

### ISSUE THREAD

**Issue by liuyuanming** [PingPlusPlus/pingpp-ios#52]
<img width="870" alt="2016-08-26 5 19 51" src="https://cloud.githubusercontent.com/assets/11534449/18000637/91eae7d2-6bb1-11e6-8fcd-7358aa0705cc.png">

**Comment by samurai00** [comment]
CoreLocation 导入这个 framework
