### ISSUE TITLE
这是为什么啊？

### ISSUE THREAD

**Issue by JsonJieLi** [PingPlusPlus/pingpp-ios#54]
"/Users/xiaohaijian/Desktop/PayPing/plugins/me.tongchia.cordova.pingpp/sdk/ios/lib/Channels/Wx/libpingpp+wx.a" not found!麻烦您回答下，谢谢

**Comment by samurai00** [comment]
微信的 sdk 已经不需要了。该插件的作者没有更新。

**Comment by JsonJieLi** [comment]
您意思是这插件是用不了的是吧？发自网易邮箱大师
            在2016年09月07日 12:38，afon 写道:微信的 sdk 已经不需要了。该插件的作者没有更新。

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/PingPlusPlus/pingpp-ios","title":"PingPlusPlus/pingpp-ios","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/PingPlusPlus/pingpp-ios"}},"updates":{"snippets":[{"icon":"PERSON","message":"@samurai00 in #54: 微信的 sdk 已经不需要了。该插件的作者没有更新。"}],"action":{"name":"View Issue","url":"https://github.com/PingPlusPlus/pingpp-ios/issues/54#issuecomment-245172998"}}}

**Comment by samurai00** [comment]
@JsonJieLi 你如果能够修改的话，应该稍微改改就可以了。
