### ISSUE TITLE
2.2.8：微信支付，取消后收不到回调！！！

### ISSUE THREAD

**Issue by Happylege** [PingPlusPlus/pingpp-ios#56]

**Comment by litaoyu** [comment]
URLScheme 填写的是什么?

**Comment by Happylege** [comment]
谢谢，我已经解决问题啦 发自网易邮箱大师 在2016年12月12日 18:13 ，litaoyu写道： URLScheme 填写的是什么? — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.
