### ISSUE TITLE
iOS 10   支付成功 收不到回调

### ISSUE THREAD

**Issue by qiyer** [PingPlusPlus/pingpp-ios#60]
iOS 支付成功 不是 iOS 9.x 时候的 弹窗了，改成 支付成功界面右上角（是右上角）就会有按钮返回。点击 返回xx应用了，收不到 ping＋＋ 的 回调了。。请速度修复啊～（微信，更新最新版本）

**Comment by samurai00** [comment]
你说的是哪个渠道的，支付宝、微信、银联还是其他的？

**Comment by qiyer** [comment]
微信

**Comment by litaoyu** [comment]
iOS 9.x 的都是有回调的么? URLScheme填写 是wx的appid么?

**Comment by qiyer** [comment]
9.x 没有 问题，对的

**Comment by qiyer** [comment]
[https://github.com/qiyer/work/blob/master/test.jpg](url)   可以看这个图片，点击右上角 返回，收不到回调

**Comment by litaoyu** [comment]
把你的QQ留一下  等会会有人加你

**Comment by ZeroDY** [comment]
我也是相同的问题，只添加了支付宝和微信，测试环境下两者都行，正式环境下支付宝可以回调，微信无法回调  qq：691352202

**Comment by isaced** [comment]
我也遇到这个问题，iOS 10 微信支付成功后不回调，有解决方案吗？

**Comment by wushenchao** [comment]
我也遇到这个问题了，请问有解决方案吗？

**Comment by yawaitlove** [comment]
这个问题解决了么？

**Comment by xiao-mu** [comment]
最新版本支付后微信收不到回调，[Pingpp handleOpenURL:url withCompletion:nil] 返回NO,支付结果不返回。

**Comment by publicBenz** [comment]
等不了了，自己先临时解决一下！传统方法，勾它。
需要的朋友可以用一下，直接引入到工程中即可


[归档.zip](https://github.com/PingPlusPlus/pingpp-ios/files/715574/default.zip)

**Comment by wushenchao** [comment]
没人解决吗？

**Comment by LuLoveMin** [comment]
同问，之前支付还能回调呢，后来又不能回调了。

**Comment by litaoyu** [comment]
@LuLoveMin  Appdelegate.m 中有添加  Pingpp的handleURL相关方法么?

**Comment by xiao-mu** [comment]
嗯  添加啦，我想问下，你们真机测试的有问题没，我想是不是你们的接口问题，是我哪地方写错啦，还是普遍问题呢？你们测试嗯有收不到回调问题没？




发自网易邮箱大师
在2017年03月24日 12:27，litaoyu 写道：

@LuLoveMin Appdelegate.m 中有添加 Pingpp的handleURL相关方法么?

**Comment by litaoyu** [comment]
微信支付没有回调  
1.检查下 charge中的 credential里的 appId  与 App中的Info.plist中填写的URLScheme 是否一致 
2.检查 Appdelegate.m中有添加Pingpp的handleURL相关方法
```
//iOS 9以下
- (BOOL)application:(UIApplication *)application
            openURL:(NSURL *)url
  sourceApplication:(NSString *)sourceApplication
         annotation:(id)annotation {
    BOOL canHandleURL = [Pingpp handleOpenURL:url withCompletion:nil];
    return canHandleURL;
}

//iOS 9 以上
- (BOOL)application:(UIApplication *)app
            openURL:(NSURL *)url
            options:(NSDictionary *)options {
    BOOL canHandleURL = [Pingpp handleOpenURL:url withCompletion:nil];
    return canHandleURL;
}
```

**Comment by litaoyu** [comment]
@LuLoveMin 检查下 charge中的 credential里的 appId 与 App中的Info.plist中填写的URLScheme 是否一致

**Comment by WangGuibin** [comment]
没有解决嘛???各位大佬最后是怎么解决的...
