### ISSUE TITLE
集成2.2.8版本后提交appstore审核时报错

### ISSUE THREAD

**Issue by crackwl8** [PingPlusPlus/pingpp-ios#61]
ERROR ITMS-90535: "Unexpected CFBundleExecutable Key. The bundle at 'Payload/XLMM.app/PassGuardCtrlBundle.bundle' does not contain a bundle executable. If this bundle intentionally does not contain an executable, consider removing the CFBundleExecutable key from its Info.plist and using a CFBundlePackageType of BNDL. If this bundle is part of a third-party framework, consider contacting the developer of the framework for an update to address this issue."

**Comment by samurai00** [comment]
把 PassGuardCtrlBundle.bundle 下的 Info.plist 删了。
