### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by shuaiwang007** [PingPlusPlus/pingpp-ios#63]
ld: library not found for -lASIHttpRequest
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by MinLee6** [comment]
Channels里面少文件。Wx

**Comment by samurai00** [comment]
@shuaiwang007 你是用的 demo 吗？demo 之前有些问题，更新了一下。或者你把 bfb 目录相关的都删了。

@MinLee6 Wx 目录整个都不需要了，wx 相关的也都可以删了。

**Comment by shuaiwang007** [comment]
ok，👌
