### ISSUE TITLE
收到短信说要升到最新版本SDK,但是好像cocoapods不支持2.2.9

### ISSUE THREAD

**Issue by WangGuibin** [PingPlusPlus/pingpp-ios#64]
Pingplusplus iOS SDK
   pod 'Pingpp', '~> 2.2.8'
   - Homepage: https://pingxx.com
   - Source:   https://github.com/PingPlusPlus/pingpp-ios.git
   - Versions: 2.2.8, 2.2.7, 2.2.6, 2.2.5, 2.2.4, 2.2.2, 2.2.1, 2.2.0, 2.1.4,
   2.1.3, 2.1.1, 2.1.0, 2.0.6, 2.0.5, 2.0.3 [master repo]
   - Subspecs:
     - Pingpp/Core (2.2.8)
     - Pingpp/ApplePay (2.2.8)
     - Pingpp/Alipay (2.2.8)
     - Pingpp/Wx (2.2.8)
     - Pingpp/UnionPay (2.2.8)
     - Pingpp/Network (2.2.8)
     - Pingpp/Cnp (2.2.8)
     - Pingpp/One (2.2.8)
     - Pingpp/Qgbc (2.2.8)
     - Pingpp/Fqlpay (2.2.8)
     - Pingpp/Mmdpay (2.2.8)
     - Pingpp/BfbWap (2.2.8)
     - Pingpp/Yeepay (2.2.8)
     - Pingpp/CmbWallet (2.2.8)
     - Pingpp/Jdpay (2.2.8)
     - Pingpp/QQWallet (2.2.8)
     - Pingpp/WebView (2.2.8)

我就想问问,升到2.2.8会有什么问题吗?

**Comment by wushenchao** [comment]
没人就我们两个

**Comment by samurai00** [comment]
2.2.9 上传失败了。会重新上传。
如果你们可以用本地 pod 的，先下载下来用本地 pod。

**Comment by wushenchao** [comment]
什么时候上传呢？着急使用

**Comment by WangGuibin** [comment]
我本地pod,编译遇到20几个报错,根据需求把不需要的几个channel去掉了,然后还有一个报错

PhaseScriptExecution Embed\ Pods\ Frameworks Build/Intermediates/JJYSPlusPlus.build/Debug-iphonesimulator/JJYSPlusPlus.build/Script-F6BF33B968F81DBD08BCE810.sh
    cd /Users/ddys/Desktop/SVN代码仓库/JJYSPlus
    /bin/sh -c /Users/ddys/Desktop/SVN代码仓库/JJYSPlus/Build/Intermediates/JJYSPlusPlus.build/Debug-iphonesimulator/JJYSPlusPlus.build/Script-F6BF33B968F81DBD08BCE810.sh

我不知道问题出在哪里了,请赐教一下啊

**Comment by samurai00** [comment]
@WangGuibin 你 Podfile 相关内容贴一下看看，是按渠道分模块写的吗

**Comment by wushenchao** [comment]
你们为什么不直接更新呢？这样大家都方便了

**Comment by yuzhiyou1990** [comment]
为什么不直接更新呢？等着用

**Comment by SuperDizzy** [comment]
pod 'Pingpp/Alipay', :git => 'https://github.com/PingPlusPlus/pingpp-ios.git'
不搭建本地 pod 可以类似这样使用，更新到2.2.9了。

**Comment by wushenchao** [comment]
@SuperDizzy  可以了

**Comment by bawn** [comment]
搜索 Pingpp 仍然只有2.2.8的

```
-> Pingpp (2.2.8)
   Pingplusplus iOS SDK
   pod 'Pingpp', '~> 2.2.8'
   - Homepage: https://pingxx.com
   - Source:   https://github.com/PingPlusPlus/pingpp-ios.git
   - Versions: 2.2.8, 2.2.7, 2.2.6, 2.2.5, 2.2.4, 2.2.2, 2.2.1, 2.2.0, 2.1.4,
   2.1.3, 2.1.1, 2.1.0, 2.0.6, 2.0.5, 2.0.3 [master repo]
   - Subspecs:
     - Pingpp/Core (2.2.8)
     - Pingpp/ApplePay (2.2.8)
     - Pingpp/Alipay (2.2.8)
     - Pingpp/Wx (2.2.8)
     - Pingpp/UnionPay (2.2.8)
     - Pingpp/Network (2.2.8)
     - Pingpp/Cnp (2.2.8)
     - Pingpp/One (2.2.8)
     - Pingpp/Qgbc (2.2.8)
     - Pingpp/Fqlpay (2.2.8)
     - Pingpp/Mmdpay (2.2.8)
     - Pingpp/BfbWap (2.2.8)
     - Pingpp/Yeepay (2.2.8)
     - Pingpp/CmbWallet (2.2.8)
```

**Comment by MickeyHub** [comment]
等待pod作者推到trunk, 临时可以用: pod ‘Pingpp’, :git=>'https://github.com/PingPlusPlus/pingpp-ios.git', :tag=>2.2.9

**Comment by LH-Liu** [comment]
从通知更新过去那么多天了，为什么Cocoapods上还没更新？@samurai00

**Comment by yuhanle** [comment]
我就来催一催的，本地Pods 也是验证不通过，不能上传到私有库呢

**Comment by samurai00** [comment]
2.2.9 已提交
