### ISSUE TITLE
使用pod 升级2.2.9 失败

### ISSUE THREAD

**Issue by wushenchao** [PingPlusPlus/pingpp-ios#65]
默认只能升级到2.2.8  当使用     pod 'Pingpp', '~> 2.2.9' 时

Analyzing dependencies
[!] Unable to satisfy the following requirements:

- `Pingpp (~> 2.2.9)` required by `Podfile`

**Comment by WangGuibin** [comment]
呵呵😑 一样的问题  Pingplusplus iOS SDK
   pod 'Pingpp', '~> 2.2.8'
   - Homepage: https://pingxx.com
   - Source:   https://github.com/PingPlusPlus/pingpp-ios.git
   - Versions: 2.2.8, 2.2.7, 2.2.6, 2.2.5, 2.2.4, 2.2.2, 2.2.1, 2.2.0, 2.1.4,
   2.1.3, 2.1.1, 2.1.0, 2.0.6, 2.0.5, 2.0.3 [master repo]
   - Subspecs:
     - Pingpp/Core (2.2.8)
     - Pingpp/ApplePay (2.2.8)
     - Pingpp/Alipay (2.2.8)
     - Pingpp/Wx (2.2.8)
     - Pingpp/UnionPay (2.2.8)
     - Pingpp/Network (2.2.8)
     - Pingpp/Cnp (2.2.8)
     - Pingpp/One (2.2.8)
     - Pingpp/Qgbc (2.2.8)
     - Pingpp/Fqlpay (2.2.8)
     - Pingpp/Mmdpay (2.2.8)
     - Pingpp/BfbWap (2.2.8)
     - Pingpp/Yeepay (2.2.8)
     - Pingpp/CmbWallet (2.2.8)
     - Pingpp/Jdpay (2.2.8)
     - Pingpp/QQWallet (2.2.8)
     - Pingpp/WebView (2.2.8)

**Comment by wushenchao** [comment]
发邮件通知让升级 pod里面还没有我也是醉了

**Comment by skybeliever** [comment]
更新失败，已经更新本地Spec,但还是找不到2.2.9

**Comment by samurai00** [comment]
2.2.9 上传失败了。会重新上传。
如果你们可以用本地 pod 的，先下载下来用本地 pod。

**Comment by wushenchao** [comment]
什么时候更新？
