### ISSUE TITLE
alipay sdk 和 阿里百川的sdk 其中的方法冲突

### ISSUE THREAD

**Issue by Gyenay** [PingPlusPlus/pingpp-ios#67]
duplicate symbol _OBJC_METACLASS_$_UTDIDKeychainItemWrapper in:
    /Users/wanmen03/allus-ios-mid/Pods/Pingpp/lib/Channels/Alipay/AlipaySDK.framework/AlipaySDK
    /Users/wanmen03/allus-ios-mid/allus/YWFramework/UTDID.framework/UTDID(UTDIDKeychainItemWrapper.o)
duplicate symbol _OBJC_CLASS_$_UTDIDPersistentConf in:
    /Users/wanmen03/allus-ios-mid/Pods/Pingpp/lib/Channels/Alipay/AlipaySDK.framework/AlipaySDK
    /Users/wanmen03/allus-ios-mid/allus/YWFramework/UTDID.framework/UTDID(UTDIDPersistentConf.o)
duplicate symbol _OBJC_METACLASS_$_UTDIDPersistentConf in:
    /Users/wanmen03/allus-ios-mid/Pods/Pingpp/lib/Channels/Alipay/AlipaySDK.framework/AlipaySDK
    /Users/wanmen03/allus-ios-mid/allus/YWFramework/UTDID.framework/UTDID(UTDIDPersistentConf.o)
duplicate symbol _OBJC_CLASS_$_UTDIDPersistentFile in:
    /Users/wanmen03/allus-ios-mid/Pods/Pingpp/lib/Channels/Alipay/AlipaySDK.framework/AlipaySDK
    /Users/wanmen03/allus-ios-mid/allus/YWFramework/UTDID.framework/UTDID(UTDIDPersistentFile.o)
duplicate symbol _OBJC_METACLASS_$_UTDIDPersistentFile in:
    /Users/wanmen03/allus-ios-mid/Pods/Pingpp/lib/Channels/Alipay/AlipaySDK.framework/AlipaySDK
    /Users/wanmen03/allus-ios-mid/allus/YWFramework/UTDID.framework/UTDID(UTDIDPersistentFile.o)
duplicate symbol _OBJC_METACLASS_$_UTDIDGTMBase64 in:
    /Users/wanmen03/allus-ios-mid/Pods/Pingpp/lib/Channels/Alipay/AlipaySDK.framework/AlipaySDK
    /Users/wanmen03/allus-ios-mid/allus/YWFramework/UTDID.framework/UTDID(UTDIDGTMBase64.o)
duplicate symbol _OBJC_CLASS_$_UTDIDGTMBase64 in:
    /Users/wanmen03/allus-ios-mid/Pods/Pingpp/lib/Channels/Alipay/AlipaySDK.framework/AlipaySDK
    /Users/wanmen03/allus-ios-mid/allus/YWFramework/UTDID.framework/UTDID(UTDIDGTMBase64.o)
ld: 34 duplicate symbols for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by samurai00** [comment]
https://doc.open.alipay.com/doc2/detail.htm?treeId=54&articleId=104509&docType=1
用下面的替换支付宝的 SDK
