### ISSUE TITLE
iOS调起支付后影响app的snapshot生成

### ISSUE THREAD

**Issue by zhangqiFromTinfinite** [PingPlusPlus/pingpp-ios#69]
不知道SDK内容是否调用了类似于ignoreSnapshotOnNextApplicationLaunch的方法，我们的app在调起微信或支付宝后，跳转，正常情况下iOS系统会生成一张此时的snapshot，在多任务模式以及跳转回来时显示这张snapshot，但是却并没有显示正确的snapshot，它显示了调用支付之前的snapshot，而且一直不会再更新这张snapshot了，直到杀掉app重启

此问题并非必现，我们只在一台iphone6s plus，系统10.0.2，上面发现了这个问题

**Comment by litaoyu** [comment]
用到的是 单纯的SDK  还是壹收款?
