### ISSUE TITLE
iOS一网通支付成功后 返回商户 不响应

### ISSUE THREAD

**Issue by bxkkk** [PingPlusPlus/pingpp-ios#71]
pingpp的版本是2.2.9 也设置了ignoreResultUrl 在一网通支付成功页面 点击返回商户 没有反应

**Comment by litaoyu** [comment]
最新版的SDK 已经修复了这个问题 你可以更新一下试试

**Comment by bxkkk** [comment]
非常感谢 更新了新的SDK 已经解决了

________________________________
发件人: litaoyu <notifications@github.com>
发送时间: 2016年12月12日 10:05:46
收件人: PingPlusPlus/pingpp-ios
抄送: ZhangTong; Author
主题: Re: [PingPlusPlus/pingpp-ios] iOS一网通支付成功后 返回商户 不响应 (#71)


最新版的SDK 已经修复了这个问题 你可以更新一下试试

―
