### ISSUE TITLE
pod install 失败

### ISSUE THREAD

**Issue by lyq226809** [PingPlusPlus/pingpp-ios#74]
xcode版本 8.2， pod版本1.1.1  安装2.2.10报如下信息

错误信息：
[!] Error installing Pingpp
[!] /usr/bin/curl -f -L -o /var/folders/g3/jr6d575525xd0_jcxh22xsvm0000gn/T/d20161219-3472-1163zz8/file.zip https://github.com/PingPlusPlus/pingpp-ios/releases/download/v2.2.10/pingpp-ios-2.2.10.zip --create-dirs --netrc-optional

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   598    0   598    0     0    297      0 --:--:--  0:00:02 --:--:--   297
  2 39.8M    2 1121k    0     0   2390      0  4:51:06  0:08:00  4:43:06     0
curl: (56) SSLRead() return error -9806

**Comment by stevenkitter** [comment]
me too . update for https please be robust

**Comment by samurai00** [comment]
因为放在 GitHub 上，所以网络不行。如果用 VPN 可以一定程度解决这个问题。
目前我们也正在找合适的托管服务器。

**Comment by stevenkitter** [comment]
@samurai00 不应该是GitHub的原因吧 我用vpn也下不来 cocoapods用了那么多都没遇到过这种情况。

**Comment by stevenkitter** [comment]
@samurai00  发邮件给我说https需要更新包，现在怒更新不了啊，难道得手动拖？

**Comment by samurai00** [comment]
VPN 还不行的话，那只能先 clone 或者下载下来，做本地 pod 了。

**Comment by lyq8023** [comment]
@samurai00  什么时候能解决呢

**Comment by jiao808813** [comment]
vpn也慢的要死，能不能行了

**Comment by shuiliang** [comment]
已经翻墙了 ,还是不行啊,更新不了...这就尴尬了

**Comment by FannyYang0507** [comment]
发现2.2.9版本以后就pod不下来了，有解决的吗？难道真的要手动导入SDK？重新按手动导入的方式再来一遍？宝宝不想啊。。。

**Comment by shuiliang** [comment]
白天怎么整都不行,凌晨的时候我用 pod update --verbose --no-repo-update     成功了安装了,现在是2.2.10, 挂不挂 vpn 都可以

**Comment by FannyYang0507** [comment]
@shuiliang 凌晨？12点以后吗？我晚上11点多试都不行，赶脚这个很不靠谱的说

**Comment by shuiliang** [comment]
我那时候弄是夜里一点多，你多试几下呗

发自我的 iPhone

**Comment by FannyYang0507** [comment]
@samurai00 如何本地pod呢？求教

**Comment by FannyYang0507** [comment]
@shuiliang 太费时间了，再试试吧，后面上线在即，看能不能赶上。。。

**Comment by samurai00** [comment]
这个现在放国内了，应该快一点了。
