### ISSUE TITLE
请问壹收款支持https自制证书吗？

### ISSUE THREAD

**Issue by stlemon** [PingPlusPlus/pingpp-ios#76]
我看clientSDK里面有这个
/**
 *  允许 https 自签证书，当你的 chargeURL 为 https 且为自签证书时使用该方法设置
 *  @param  allowInvalidCertificates BOOL
 */
+ (void)setAllowInvalidCertificates:(BOOL)allowInvalidCertificates;
但是壹收款里面没有，是壹收款不支持吗？
再就是这里只是设置是否允许，但是请求我的server的时候得带上自制证书才行吧？要怎么处理？
打扰了，非常感谢！

**Comment by samurai00** [comment]
壹收款不支持这个。
