### ISSUE TITLE
跟友盟分析冲突UTDID

### ISSUE THREAD

**Issue by natewang** [PingPlusPlus/pingpp-ios#78]
与友盟使用的UTDID冲突，可查看alipay的支付sdk，改为不使用源码引用的SDK。

**Comment by samurai00** [comment]
http://aopsdkdownload.cn-hangzhou.alipay-pub.aliyun-inc.com/demo/AlipaySDK_No_UTDID.zip?spm=a219a.7629140.0.0.Anai4c&file=AlipaySDK_No_UTDID.zip

拿这个替换。

**Comment by natewang** [comment]
@samurai00 这样源码直接引入，更新很不方便啊
