### ISSUE TITLE
application openURL 没有回调

### ISSUE THREAD

**Issue by guolijun** [PingPlusPlus/pingpp-ios#8]

**Comment by guolijun** [comment]
找到了。。。
Demo 里回调的是：
application: handleOpenURL: sourceApplication: annotation:
我的代码回调的是：application: handleOpenURL

**Comment by samurai00** [comment]
应该是这个：`- application:openURL:sourceApplication:annotation:`

**Comment by guolijun** [comment]
哦！我搞错了，谢谢。
