### ISSUE TITLE
和阿里云的sdk 有个库冲突，重复了，你们应该做个重命名

### ISSUE THREAD

**Issue by gank0326** [PingPlusPlus/pingpp-ios#82]

**Comment by samurai00** [comment]
因为调用支付宝需要支付宝的 sdk，可能与阿里其他的 sdk 冲突。如果出现 UTDID 相关冲突，请使用 没有 UTDID 的版本替换 sdk 中 alipay 相应的文件。https://docs.open.alipay.com/54/104509

**Comment by samurai00** [comment]
可以使用 `Pingpp/AlipayNoUTDID` 解决该问题
