### ISSUE TITLE
往ITC上传时报错

### ISSUE THREAD

**Issue by lacklock** [PingPlusPlus/pingpp-ios#83]
返回的错误信息：
[Transporter Error Output]: ERROR ITMS-90542: "Invalid CFBundleSupportedPlatforms value. The key 'CFBundleSupportedPlatforms' in the Info.plist file in bundle 'Payload/Right-iOS.app/Pingpp.bundle' contains an invalid value '[iPhoneSimulator]'. Consider removing the CFBundleSupportedPlatforms key from the Info.plist. If this bundle is part of a third-party framework, consider contacting the developer of the framework for an update to address this issue."

这里说你们的info.plist里面有非法的key [iPhoneSimulator]，是你们的问题吗？

**Comment by wanjiehuizhaofang** [comment]
对，我们现在打的包就是这个问题，用的是2.2.14这个tag ，希望能给解决下，

**Comment by lacklock** [comment]
@wanjiehuizhaofang https://github.com/lacklock/pingpp-ios
我fork了一份改好了。你只要指定到这个git就可以了
这个公司的技术支持真的是有点可笑的慢
