### ISSUE TITLE
ITMS-90542 - Invalid CFBundleSupportedPlatforms value

### ISSUE THREAD

**Issue by wanjiehuizhaofang** [PingPlusPlus/pingpp-ios#84]
ITMS-90542 - Invalid CFBundleSupportedPlatforms value
Invalid CFBundleSupportedPlatforms value. The key 'CFBundleSupportedPlatforms' in the Info.plist file in bundle 'Payload/Huifenqi.app/Pingpp.bundle' contains an invalid value '[iPhoneSimulator]'. Consider removing the CFBundleSupportedPlatforms key from the Info.plist. If this bundle is part of a third-party framework, consider contacting the developer of the framework for an update to address this issue.

**Comment by MataHu** [comment]
replace iPhoneSimulator with iPhoneOS（CFBundleSupportedPlatforms = iPhoneOS）
