### ISSUE TITLE
我是在忍不住想喷人了

### ISSUE THREAD

**Issue by SteveUXC** [PingPlusPlus/pingpp-ios#86]
请问一下pod工程为什么没有pod文件啊？还有.DS_Store文件是什么鬼，不会用Git我没啥说的,那就不要瞎搞，老老实实弄个压缩包多好。非要装x，容易被喷啊

**Comment by samurai00** [comment]
这个是 pod 库。不是 pod 工程。你直接 pod install 就好。你要下载下来做本地 pod 那也 OK。不知道你所谓的 pod 文件是不是 Podfile

**Comment by samurai00** [comment]
另外，.DS_Store 这个文件我们检查过了，是没有上传到 git 的。
