### ISSUE TITLE
alipaysdk 和 pingpp内部的sdk冲突，有什么解决办法

### ISSUE THREAD

**Issue by karosLi** [PingPlusPlus/pingpp-ios#90]
The 'Pods-App' target has frameworks with conflicting names: alipaysdk.framework

背景：
我们需要继承支付宝登录功能，需要引入alipaysdk，并且alipaysdk被加入到了我们的社会化分享组件里面了，组件是没有问题的，一旦这个组件和我们的支付组件（包含pingpp）一起被引入主工程，就会冲突，我目前能想到的是，直接在社会化组件里面引用pingpp/alipay,但是这样看起来很奇怪，有什么好的解决办法？

**Comment by samurai00** [comment]
可以使用 `Pingpp/AlipayNoUTDID`
