### ISSUE TITLE
微信支付没有正确回调,已经设置了不同的urlScheme为啥还会回调到原来的应用

### ISSUE THREAD

**Issue by WangGuibin** [PingPlusPlus/pingpp-ios#91]
事情是这样的,公司想两个应用共享一个收款账号,所以支付这一块就直接挪用了另一个应用的,现在支付都能支付成功,就是有点尴尬的是,支付完成或者是取消支付的时候, 它会提示跳转到手机里的另一个应用里去,回调的不是我想的那样, 这个问题是Ping++的问题还是微信的问题啊, 我这边参数就这么几个,然后找文档也找不着相关的说明, 只是说urlScheme要设置复杂一点,我试了几次了都... 所以来问问官方.

**Comment by stlemon** [comment]
被跳转APP的scheme是在targets-> info -> URL Types-> URL Schemes 设置的，这个schemes与ping++参数里填写的一致才行，而且你两个应用不能一样。

**Comment by samurai00** [comment]
scheme 不能共用。共用的话，无法自己选择跳回到哪一个 app。这个没办法，只能申请两套支付参数。

**Comment by WangGuibin** [comment]
感谢大大们的回答,公司已经申请两套参数了
