### ISSUE TITLE
pingpp v2.2.22 奔溃问题

### ISSUE THREAD

**Issue by objbee** [PingPlusPlus/pingpp-ios#95]
iPhone 6s Plus，iOS 9。

问题：调用 `+ (void)createPayment:(NSObject *)charge viewController (UIViewController*)viewController appURLScheme:(NSString *)scheme withCompletion:(PingppCompletion)completionBlock;` 崩溃。

报错：`[UIApplication use openURL:options:completionHandler:] unrecognized selector sent to instance`。

其他：v2.2.21 正常。

**Comment by Deng607** [comment]
更新一个新的版本号不是更好。 用同一个版本号，只是替换了一下SDK包， 原先pod过2.2.22有问题的包，如果没有做cocoapods缓存清理， pod  update  也会一直有问题的包。

**Comment by samurai00** [comment]
一般都会更新版本号的。部分特殊情况可能会直接更新源码包。
