### ISSUE TITLE
Xcode10上引入pingpp库失败

### ISSUE THREAD

**Issue by hrk1988** [PingPlusPlus/pingpp-ios#96]
建立了一个Demo工程，只在pod中引用pingpp库，构建时提示报错，信息如下：
duplicate symbol l032 in:
    /Users/fanggeek/Documents/Demos/pingppDemo/Pods/Pingpp/lib/Dependencies/Network/libpingpp+network.a(PingppURLResponseInternal.o)
    /Users/fanggeek/Documents/Demos/pingppDemo/Pods/Pingpp/lib/Channels/UnionPay/libpingpp+up.a(PingppInternal+Up.o)
duplicate symbol l120 in:
    /Users/fanggeek/Documents/Demos/pingppDemo/Pods/Pingpp/lib/Dependencies/Network/libpingpp+network.a(PingppHttpClient.o)
    /Users/fanggeek/Documents/Demos/pingppDemo/Pods/Pingpp/lib/Dependencies/Network/libpingpp+network.a(PingppHttpConnection.o)
duplicate symbol l121 in:
    /Users/fanggeek/Documents/Demos/pingppDemo/Pods/Pingpp/lib/Dependencies/Network/libpingpp+network.a(PingppHttpClient.o)
    /Users/fanggeek/Documents/Demos/pingppDemo/Pods/Pingpp/lib/Dependencies/Network/libpingpp+network.a(PingppHttpConnection.o)
duplicate symbol l280 in:
    /Users/fanggeek/Documents/Demos/pingppDemo/Pods/Pingpp/lib/libpingppcore.a(PingppUtil.o)
    /Users/fanggeek/Documents/Demos/pingppDemo/Pods/Pingpp/lib/libpingppcore.a(PingppInternal.o)
duplicate symbol l281 in:
    /Users/fanggeek/Documents/Demos/pingppDemo/Pods/Pingpp/lib/libpingppcore.a(PingppUtil.o)
    /Users/fanggeek/Documents/Demos/pingppDemo/Pods/Pingpp/lib/libpingppcore.a(PingppInternal.o)
duplicate symbol l282 in:
    /Users/fanggeek/Documents/Demos/pingppDemo/Pods/Pingpp/lib/libpingppcore.a(PingppUtil.o)
    /Users/fanggeek/Documents/Demos/pingppDemo/Pods/Pingpp/lib/libpingppcore.a(PingppInternal.o)
duplicate symbol l283 in:
    /Users/fanggeek/Documents/Demos/pingppDemo/Pods/Pingpp/lib/libpingppcore.a(PingppUtil.o)
    /Users/fanggeek/Documents/Demos/pingppDemo/Pods/Pingpp/lib/libpingppcore.a(PingppInternal.o)
duplicate symbol l284 in:
    /Users/fanggeek/Documents/Demos/pingppDemo/Pods/Pingpp/lib/libpingppcore.a(PingppUtil.o)
    /Users/fanggeek/Documents/Demos/pingppDemo/Pods/Pingpp/lib/libpingppcore.a(PingppInternal.o)
duplicate symbol l285 in:
    /Users/fanggeek/Documents/Demos/pingppDemo/Pods/Pingpp/lib/libpingppcore.a(PingppUtil.o)
    /Users/fanggeek/Documents/Demos/pingppDemo/Pods/Pingpp/lib/libpingppcore.a(PingppInternal.o)
duplicate symbol l286 in:
    /Users/fanggeek/Documents/Demos/pingppDemo/Pods/Pingpp/lib/libpingppcore.a(PingppUtil.o)
    /Users/fanggeek/Documents/Demos/pingppDemo/Pods/Pingpp/lib/libpingppcore.a(PingppInternal.o)
duplicate symbol l287 in:
    /Users/fanggeek/Documents/Demos/pingppDemo/Pods/Pingpp/lib/libpingppcore.a(PingppUtil.o)
    /Users/fanggeek/Documents/Demos/pingppDemo/Pods/Pingpp/lib/libpingppcore.a(PingppInternal.o)
duplicate symbol l288 in:
    /Users/fanggeek/Documents/Demos/pingppDemo/Pods/Pingpp/lib/libpingppcore.a(PingppUtil.o)
    /Users/fanggeek/Documents/Demos/pingppDemo/Pods/Pingpp/lib/libpingppcore.a(PingppInternal.o)
ld: 12 duplicate symbols for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by samurai00** [comment]
Xcode 10 正式版吗

**Comment by hrk1988** [comment]
Xcode 10 Bate5 待会我再下载一个正式版验证一次

**Comment by hrk1988** [comment]
> Xcode 10 正式版吗

Xcode 10 Bate5 待会我再下载一个正式版验证一次

**Comment by samurai00** [comment]
@hrk1988 beta 5 确实有这个问题，正式版其实我们这边也还在更新过程中...

**Comment by hrk1988** [comment]
@samurai00 Xcode10 正式版正常了

**Comment by samurai00** [comment]
@hrk1988 我这边也试了。确实好了，当时就认为是 Xcode 有问题，看来这想法是对的。
如果后续有问题，可以继续反馈，谢谢。

**Comment by OrangeFlavoredColdCoffee** [comment]
@samurai00 你好，我这边昨天Xcode自动升级10.2之后 ping++就编译错误，和上面错误类似。

![image](https://user-images.githubusercontent.com/15223345/55217657-00b63500-523b-11e9-82e3-8e9f6f8afd68.png)
![image](https://user-images.githubusercontent.com/15223345/55217680-10ce1480-523b-11e9-8650-484b7fcb4217.png)
请问如何解决呢

**Comment by samurai00** [comment]
是使用的 cocoapods 吗？还是其他方式。

我这边使用 Xcode Version 10.2 (10E125)，没有出现报错，引用了以下模块

```ruby
    pod 'Pingpp/Alipay'
    pod 'Pingpp/UnionPay'
    pod 'Pingpp/ApplePay'
    pod 'Pingpp/QQWallet'
    pod 'Pingpp/CmbWallet'
    pod 'Pingpp/BfbWap'
    pod 'Pingpp/Yeepay'
    pod 'Pingpp/Jdpay'
    pod 'Pingpp/CcbPay'
    pod 'Pingpp/Agreement'
```

你这个看起来是重复导入了 cmbkeybord 和 alipaysdk 提供的库。

**Comment by OrangeFlavoredColdCoffee** [comment]
@samurai00 其他方式，没错应该就是这两个库
![image](https://user-images.githubusercontent.com/15223345/55218301-a7e79c00-523c-11e9-8f7b-1a5b3f6209fc.png)
![image](https://user-images.githubusercontent.com/15223345/55218315-b03fd700-523c-11e9-993a-fbea91356970.png)
