### ISSUE TITLE
pod install在install PingppAlipaySDK 时会返回403

### ISSUE THREAD

**Issue by singleD** [PingPlusPlus/pingpp-ios#98]
从2.2.20开始（现在的2.2.27）也是，执行pod install会报如下的错误：
![image](https://user-images.githubusercontent.com/12008819/63004651-78fd5a00-bead-11e9-956f-c88ab11ad48f.png)
看上去是阿里云权限的问题

**Comment by singleD** [comment]
应该是PingppAlipaySDK的source无法访问

**Comment by samurai00** [comment]
已经修复。阿里云 OSS 一个 bucket 的权限设置错误了。
